package:
  name: arachnid
  version: %%version%%

source:
  fn: arachnid-0.1.2.tar.gz
  url: http://
  md5: 8eac87462c7bec8b89021b723207c623

build:
  number: 1

requirements:
  build:
    - cmake        [unix]
    - numpy
    - jpeg
    - zlib
    - libpng
  run:
    - python
    - numpy
    - jpeg
    - zlib         [unix]
    - libpng

about:
  home: http://code.google.com/p/arachnid/
  license: BSD